//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveViewPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_event
    {
        public long id { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<sbyte> subtype { get; set; }
        public string cameraid { get; set; }
        public string time { get; set; }
        public string imgurl1 { get; set; }
        public string imgurl2 { get; set; }
        public string imgurl3 { get; set; }
        public string videourl { get; set; }
    }
}
