//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveViewPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_user_role_action
    {
        public int role_id { get; set; }
        public int action_id { get; set; }
    }
}
