//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveViewPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_nvr
    {
        public string ip { get; set; }
        public long capacity { get; set; }
        public string writemode { get; set; }
        public System.DateTime currenttime { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<int> max_input { get; set; }
    }
}
