//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveViewPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_video_processor
    {
        public string ip { get; set; }
        public string user { get; set; }
        public string passwork { get; set; }
        public Nullable<int> config_port { get; set; }
        public Nullable<int> stream_number { get; set; }
        public string description { get; set; }
        public string password { get; set; }
    }
}
