//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSWorkStation.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_vehicle
    {
        public sbyte type { get; set; }
        public string name { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> length { get; set; }
        public string description { get; set; }
    }
}
