//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSWorkStation.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_ipdec_screen
    {
        public sbyte screenid { get; set; }
        public Nullable<sbyte> layout { get; set; }
    }
}
