//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSWorkStation.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_vms
    {
        public string id { get; set; }
        public string ip { get; set; }
        public int port { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string location { get; set; }
        public string description { get; set; }
        public string controller { get; set; }
    }
}
