//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSWorkStation.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_event_source
    {
        public int cam_id { get; set; }
        public Nullable<sbyte> status { get; set; }
        public string video_processor_ip { get; set; }
        public string video_output_url { get; set; }
        public string image_output_url { get; set; }
    }
}
