//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSWorkStation.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_event_lookup_car
    {
        public int id { get; set; }
        public Nullable<int> vehicle_group { get; set; }
        public string type { get; set; }
        public string vitype { get; set; }
    }
}
