//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSWorkStation.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_evt_speedevent
    {
        public int seqnum { get; set; }
        public int cameraid { get; set; }
        public string imgurl1 { get; set; }
        public string imgurl2 { get; set; }
        public string eventtime { get; set; }
        public string xmldata { get; set; }
        public string videourl { get; set; }
    }
}
