//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSWorkStation.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_nvr_videostorage
    {
        public string id { get; set; }
        public string filename { get; set; }
        public string starttime { get; set; }
        public string duration { get; set; }
        public double filesize { get; set; }
        public System.DateTime ts { get; set; }
    }
}
