//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackPlugin.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class cctvEntities : DbContext
    {
        public cctvEntities()
            : base("name=cctvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<its_cam> its_cam { get; set; }
        public DbSet<its_cam_group> its_cam_group { get; set; }
        public DbSet<its_event> its_event { get; set; }
        public DbSet<its_event_info> its_event_info { get; set; }
        public DbSet<its_event_lookup_car> its_event_lookup_car { get; set; }
        public DbSet<its_event_source> its_event_source { get; set; }
        public DbSet<its_ipdec_screen> its_ipdec_screen { get; set; }
        public DbSet<its_login> its_login { get; set; }
        public DbSet<its_nvr> its_nvr { get; set; }
        public DbSet<its_user> its_user { get; set; }
        public DbSet<its_user_action> its_user_action { get; set; }
        public DbSet<its_user_role> its_user_role { get; set; }
        public DbSet<its_vehicle_group> its_vehicle_group { get; set; }
        public DbSet<its_vos_sources> its_vos_sources { get; set; }
        public DbSet<its_vos_text_position> its_vos_text_position { get; set; }
        public DbSet<its_cam_type> its_cam_type { get; set; }
        public DbSet<its_event_subtype> its_event_subtype { get; set; }
        public DbSet<its_event_type> its_event_type { get; set; }
        public DbSet<its_ipdec_session> its_ipdec_session { get; set; }
        public DbSet<its_ipdec_sources> its_ipdec_sources { get; set; }
        public DbSet<its_nvr_videostorage> its_nvr_videostorage { get; set; }
        public DbSet<its_speed_cam> its_speed_cam { get; set; }
        public DbSet<its_user_role_action> its_user_role_action { get; set; }
        public DbSet<its_vehicle> its_vehicle { get; set; }
        public DbSet<its_video_processor> its_video_processor { get; set; }
        public DbSet<its_vms> its_vms { get; set; }
        public DbSet<its_vms_resource> its_vms_resource { get; set; }
        public DbSet<its_vms_resource_type> its_vms_resource_type { get; set; }
        public DbSet<its_vms_type> its_vms_type { get; set; }
        public DbSet<its_event_axis> its_event_axis { get; set; }
        public DbSet<its_video_processing> its_video_processing { get; set; }
    
        public virtual int Get_CameraUrl(Nullable<sbyte> eventtype, string camid, string timeget)
        {
            var eventtypeParameter = eventtype.HasValue ?
                new ObjectParameter("eventtype", eventtype) :
                new ObjectParameter("eventtype", typeof(sbyte));
    
            var camidParameter = camid != null ?
                new ObjectParameter("camid", camid) :
                new ObjectParameter("camid", typeof(string));
    
            var timegetParameter = timeget != null ?
                new ObjectParameter("timeget", timeget) :
                new ObjectParameter("timeget", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Get_CameraUrl", eventtypeParameter, camidParameter, timegetParameter);
        }
    
        public virtual int sp_checkAccount(string name, string pass)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_checkAccount", nameParameter, passParameter);
        }
    
        public virtual int sp_getAllCamera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getAllCamera");
        }
    
        public virtual int sp_GetCambyID(string idcam)
        {
            var idcamParameter = idcam != null ?
                new ObjectParameter("Idcam", idcam) :
                new ObjectParameter("Idcam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetCambyID", idcamParameter);
        }
    
        public virtual ObjectResult<ComplexType1> GetAllCamera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComplexType1>("GetAllCamera");
        }
    
        public virtual int sp_GetAllVms_Resource()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetAllVms_Resource");
        }
    }
}
