//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackPlugin.EntityFramework
{
    using System;
    
    public partial class ComplexType1
    {
        public string id { get; set; }
        public sbyte type { get; set; }
        public string ip { get; set; }
        public string cameraurl { get; set; }
        public string group_name { get; set; }
    }
}
