//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_cam
    {
        public string id { get; set; }
        public string name { get; set; }
        public sbyte type { get; set; }
        public string ip { get; set; }
        public string viewurl { get; set; }
        public string recordurl { get; set; }
        public string cameraurl { get; set; }
        public int recordmode { get; set; }
        public int cliplength { get; set; }
        public int clipremovetime { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public string position { get; set; }
        public string brand { get; set; }
        public Nullable<int> group_id { get; set; }
        public string nvr_ip { get; set; }
    }
}
