//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_vos_sources
    {
        public string cameraip { get; set; }
        public string inputurl { get; set; }
        public string inputname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string outputurl { get; set; }
        public Nullable<int> outputframewidth { get; set; }
        public Nullable<int> outputframeheight { get; set; }
        public string outputcodec { get; set; }
        public Nullable<int> outputframerate { get; set; }
        public byte status { get; set; }
    }
}
