//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_user
    {
        public string username { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public int sex { get; set; }
        public System.DateTime birthday { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public System.DateTime currenttime { get; set; }
        public string role { get; set; }
    }
}
