//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_video_processing
    {
        public string video_processor_ip { get; set; }
        public Nullable<int> stream_index { get; set; }
        public string camera_id { get; set; }
        public Nullable<long> status { get; set; }
        public string video_output_url { get; set; }
        public string image_output_url { get; set; }
    }
}
