//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_vos_text_position
    {
        public int laneidpos { get; set; }
        public Nullable<int> staffnamepos { get; set; }
        public Nullable<int> timestamppos { get; set; }
        public Nullable<int> vehicleclasspos { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> platenumber { get; set; }
        public string status { get; set; }
    }
}
