//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_event_axis
    {
        public long id { get; set; }
        public long type { get; set; }
        public string cameraid { get; set; }
        public string timebegin { get; set; }
        public string timeend { get; set; }
        public string imgurl { get; set; }
    }
}
