//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaybackPlugin.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class its_ipdec_session
    {
        public Nullable<long> Id { get; set; }
        public string url { get; set; }
        public byte screenid { get; set; }
        public byte position { get; set; }
    }
}
